{
 "title": "ToDo App Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CSRF Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(csrf_failures_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Add Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "todo_app_requests_total{instance=\"devsecops-app-892127943351.europe-west2.run.app:443\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Request Latency",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (rate(todo_add_request_latency_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}